#inherit_from: .rubocop_todo.yml

# rubocop:disable all
# rubocop: enable all

#AllCops:
#  Exclude:
#    - config/initializers/*.rb
#    - config/initializers/**/*.rb

 Metrics/LineLength:
   Enabled: false

 FactoryBot/AttributeDefinedStatically:
   Enabled: false