development: &default
  database: jewlercrm-dev
  adapter: postgresql
  pool: 10
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: jewlercrm-dev

test:
  <<: *default
  database: jewlercrm-test

production-local:
  <<: *default
  database: jewlercrm-dev

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: jeweler-staging-server_production
  username: jeweler-staging-server
  password: <%= ENV['JEWELER-STAGING-SERVER_DATABASE_PASSWORD'] %>